# Generated by Django 5.1.5 on 2025-01-19 08:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_emailverification'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EmailVerification',
        ),
    ]
