version: '3.0'
services:
  service-db:
    image: postgres:13
    environment:
      POSTGRES_DB: auto_school
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    ports:
      - "5434:5432"
    restart: always
    volumes:
      - /data:/var/lib/postgresql/data

volumes:
  db-data: