version: '3.0'
services:
  service-db:
    image: postgres:13
    environment:
      POSTGRES_DB: auto_school
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - "5434:5432"
    restart: always
    volumes:
      - /data:/var/lib/postgresql/data

  service-web:
    image: app
    container_name: app
    build:
      context: .
      dockerfile: Dockerfile
    command: ["gunicorn", "myproject.wsgi:application", "--bind", "0.0.0.0:8000"]
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - service-db
    environment:
      POSTGRES_DB: auto_school
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      DATABASE_HOST: service-db
      DATABASE_PORT: 5432
      SECRET_KEY: 'django-insecure-qq_m4^j#pqs_tevf&!_$ccclhyv5zvp-06+o(pt@)%f%_wmo_w'

volumes:
  db-data: