# Generated by Django 5.1.5 on 2025-02-06 20:29

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lessonenrollment',
            name='car_brand',
            field=models.CharField(default='Не указано', max_length=50, verbose_name='Марка машины'),
        ),
        migrations.AddField(
            model_name='lessonenrollment',
            name='car_number',
            field=models.CharField(default='А000АА00', max_length=10, validators=[django.core.validators.RegexValidator(message='Гос номер должен быть в формате: А123БВ45 или А123БВ456', regex='^[АВЕКМНОРСТУХ]\\d{3}[АВЕКМНОРСТУХ]{2}\\d{2,3}$')], verbose_name='Гос номер машины'),
        ),
    ]
